### ISSUE TITLE
Combine with other sw.js file?

### ISSUE THREAD

**Issue by bpmottathai** [souldanger/jekyll-pwa-workbox#6]
Hi, thanks for making this plugin. I have already a service worker file for [onesignal](https://onesignal.com/). can I put this plugin's service worker js code in sw.js file of that or can I use as a separate one.

**Comment by souldanger** [comment]
@bpmottathai 
We have not tested anything like this before. I'd say it depends on what you would lke to broadcast, as ´´broadcastUpdate´´ will probably not do the trick with a 'onesignal' script.
Therefore why not try running both service workers.
Please let us know if it works or provide onesignal scripts and we test for you.

**Comment by bpmottathai** [comment]
my sw.js is 
```
importScripts('https://cdn.onesignal.com/sdks/OneSignalSDKWorker.js');
```

>Therefore why not try running both service workers.
How to do it? can I add your service worker js in onesignal sw js?

**Comment by souldanger** [comment]
Just try to run both service workers side by side and see what console says.
Do you have the onesignal script running actively on a website I can have a look at?

**Comment by bpmottathai** [comment]
https://news.justinechacko.in

**Comment by souldanger** [comment]
Did you test running both onesignal and workbox?

**Comment by bpmottathai** [comment]
To clarify I get A2HS notification and onesignal notification. But can I enable push notifications without onesignal. I plan to remove onesignal and implement firebase cloud messaging. I also have an app button in navbar. I think it working, and in some device not. Did you test my site? Can you link me to a guide to use firebase cloud messaging?

**Comment by souldanger** [comment]
Well, I am no Firebase expert at all, but according to their features it uses In-App Messaging, which is not the same as Push, but may perfectly serve your needs. I am sure you'll find a demo page to test locally.
Maybe also check out Angular.
