### ISSUE TITLE
Is it possible to send notifications to users

### ISSUE THREAD

**Issue by bpmottathai** [souldanger/jekyll-pwa-workbox#8]
Hi,
If I enabled this plugin in my site, will it prompt user to allow or deny to notification like below
![image](https://miro.medium.com/max/1044/1*Js9e-HXbKUR-aMG-EJUJfQ.png)
Or how can I send notifications to subscribed/installed users? Does user need to install this by clicking A2HS prompt to get notifications? I am totally new to this, hence the confusion...

**Comment by souldanger** [comment]
correct - bear in mind that this will not work with all browsers!
A crossbrowser solution can be something like Angular or Firebase, et cetera.
